---

- name: gather facts
  setup:
  tags: always


- name: install pkgs
  package:
    name: "{{item}}"
  loop: "{{ _util_pkgs[ansible_pkg_mgr] + extra_pkgs[ansible_pkg_mgr] }}"
  register: task
  retries: 3
  delay: 1
  until: task is success


- name: apt builddep
  become: yes
  when: 'ansible_pkg_mgr == "apt"'
  tags: apt
  block:

    - name: apt repository enable source pkgs
      apt_repository:
        repo: deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_lsb.codename }} main

    - name: apt-get build-dep
      apt:
        update_cache: yes
        cache_valid_time: 3600
        state: build-dep
        # apt.name support list, so no need to join
        name: "{{ builddep_pkgs[ansible_pkg_mgr] }}"
      register: task
      retries: 3
      delay: 1
      until: task is success


- name: yum builddep
  become: yes
  when: 'ansible_pkg_mgr == "yum"'
  tags: yum
  block:

    - name: remove yum.pid
      file:
        path: /var/run/yum.pid
        state: absent

    - name: yum-builddep
      command: 'yum-builddep -y -q {{ builddep_pkgs[ansible_pkg_mgr]|join(" ") }}'


- name: dnf builddep
  become: yes
  when: 'ansible_pkg_mgr == "dnf"'
  tags: dnf
  block:

    - name: dnf builddep
      command: 'dnf builddep {{ builddep_pkgs[ansible_pkg_mgr]|join(" ") }}'


- name: 'git clone -b {{ git_repo_version }} --depth {{ git_repo_depth }} {{ git_repo_url }} {{ git_repo_dest }}'
  tags: git-clone
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ git_repo_dest }}"
    version: "{{ git_repo_version }}"
    depth: "{{ git_repo_depth }}"


- name: 'run build commands in loop'
  become: yes
  command: "{{ item }}"
  args:
    chdir: "{{ git_repo_dest }}"
  loop:
      - "{{ command_distclean }}"
      - "{{ command_configure }}"
      - "{{ command_compile }}"
      - "{{ command_install }}"
      - "{{ command_link }}"
      - "{{ command_check }}"
